---
version: "2"
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "errname"
    - "errorlint"
    - "goprintffuncname"
    - "gosec"
    - "importas"
    - "makezero"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "tparallel"
    - "unconvert"
    - "usetesting"
    - "wastedassign"
    - "whitespace"
  settings:
    revive:
      rules:
        - name: "unused-parameter"
          disabled: true
    rowserrcheck:
      packages:
        - "github.com/jmoiron/sqlx"
        - "github.com/jackc/pgx"
  exclusions:
    generated: "lax"
    presets:
      - "comments"
      - "common-false-positives"
      - "legacy"
      - "std-error-handling"
    rules:
      - linters:
          - "errcheck"
        text: "tx.Rollback()"
      - linters:
          - "staticcheck"
        path: "internal/services/"
        text: "SA1019"
      - linters:
          - "staticcheck"
        path: "internal/middleware/consistency/"
        text: "SA1019"
      - linters:
          - "staticcheck"
        path: "pkg/proto/core/v1/core.pb.validate.manual.go"
        text: "ST1003"
      - linters:
          - "revive"
        path: "pkg/proto/core/v1/core.pb.validate.manual.go"
        text: "var-naming"
      - linters:
          - "revive"
        text: 'receiver-naming: receiver name \S+ should be consistent with previous receiver name \S+ for invalid-type'
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
formatters:
  enable:
    - "gofumpt"
    - "goimports"
  settings:
    goimports:
      local-prefixes:
        - "github.com/authzed/spicedb"
  exclusions:
    generated: "lax"
    paths:
      - "third_party$"
      - "builtin$"
      - "examples$"
