---
name: "CLA"
on:  # yamllint disable-line rule:truthy
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"
  merge_group:
    types:
      - "checks_requested"
permissions:
  contents: "read"
jobs:
  cla:
    name: "Check Signature"
    runs-on: "depot-ubuntu-24.04-small"
    steps:
      - uses: "authzed/actions/cla-check@9013d08e1002d122cc87f21d9ed43063555642d0" # main
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          cla_assistant_token: "${{ secrets.CLA_ASSISTANT_ACCESS_TOKEN }}"
