---
name: "Lint"
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "!dependabot/*"
      - "main"
  pull_request:
    branches: ["*"]
  merge_group:
    types:
      - "checks_requested"
permissions:
  contents: "read"
jobs:
  go-license-check:
    name: "License Check"
    runs-on: "depot-ubuntu-24.04-small"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
      - uses: "authzed/actions/setup-go@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
      - name: "Check Licenses"
        uses: "authzed/actions/go-license-check@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
        with:
          ignore: "buf.build"  # Has no license information

  go-lint:
    name: "Lint Go"
    runs-on: "depot-ubuntu-24.04-4"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
      - uses: "authzed/actions/setup-go@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
      - name: "Lint Go"
        run: "go run mage.go lint:go"
      - uses: "chainguard-dev/actions/nodiff@708219d4822f33611ac1a2653815cc10e1ab54a6" # main
        with:
          path: ""
          fixup-command: "go run mage.go lint:go"

  extra-lint:
    name: "Lint YAML & Markdown"
    runs-on: "depot-ubuntu-24.04-small"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
      - uses: "authzed/actions/setup-go@11667c9b2e8b3649ad2af4d788e57d18f8e8eaf1" # main
      - name: "Lint Everything Else"
        run: "go run mage.go lint:extra"
      - uses: "chainguard-dev/actions/nodiff@708219d4822f33611ac1a2653815cc10e1ab54a6" # main
        with:
          path: ""
          fixup-command: "go run mage.go lint:extra"
