---
name: "Build WASM"
on:  # yamllint disable-line rule:truthy
  release:
    types: ["created"]
permissions:
  contents: "read"
jobs:
  build:
    name: "Build WASM"
    runs-on: "depot-ubuntu-24.04-small"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          ref: "${{ env.GITHUB_SHA }}"
      - uses: "authzed/actions/setup-go@main"
      - name: "Build WASM"
        run: "go run mage.go build:wasm"
      - uses: "shogo82148/actions-upload-release-asset@v1"
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "dist/*"
