---
name: "Build WASM"
on:  # yamllint disable-line rule:truthy
  release:
    types: ["created"]
permissions:
  contents: "read"
jobs:
  build:
    name: "Build WASM"
    runs-on: "depot-ubuntu-24.04-small"
    permissions:
      contents: "write"
    steps:
      - uses: "actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493" # v4.2.2
        with:
          ref: "${{ env.GITHUB_SHA }}"
      - uses: "authzed/actions/setup-go@93e4256104107969575e8a377425b16313e8cc72" # main
      - name: "Build WASM"
        run: "go run mage.go build:wasm"
      - uses: "shogo82148/actions-upload-release-asset@610b1987249a69a79de9565777e112fb38f22436" # v1.8.1
        with:
          upload_url: "${{ github.event.release.upload_url }}"
          asset_path: "dist/*"
